apiVersion: v1
kind: ConfigMap
metadata:
  name: green-config
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; background: #e3f3ff">
        <h1>Green Deployment</h1>
        <p>You are being served by the Green version.</p>
      </body>
    </html>
